using System;
using System.Collections.Generic;
using System.Text;

namespace PamposTools.SaferPay.Models
{
    public class Alias
    {
        /// <summary>
        /// Id generator to be used by Saferpay.
        /// Possible values: MANUAL, RANDOM, RANDOM_UNIQUE.
        /// Example: MANUAL
        /// </summary>
        public string IdGenerator { get; set; }

        /// <summary>
        /// Alias id to be used for registration if not generated by Saferpay. Mandatory if IdGenerator is 'MANUAL'. This value is case-insensitive.
        /// Id[1..40]
        /// Example: alias35nfd9mkzfw0x57iwx
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Number of days this card is to be stored within Saferpay. If not filled, the default lifetime will be used.
        /// Range: inclusive between 1 and 1600
        /// Example: 1000 
        /// </summary>
        public int Lifetime { get; set; }
    }
}
