using System;
using System.Collections.Generic;
using System.Text;

namespace PamposTools.SaferPay.Models
{
    public class ThreeDs
    {
        /// <summary>
        /// Indicates, whether the payer has successfuly authenticated him/herself or not.
        /// </summary>
        public bool Authenticated { get; set; }

        /// <summary>
        /// Indicates whether liability shift to issuer is possible or not. Not present if PaymentMeans container was not present in Initialize request. 
        /// True, if liability shift to issuer is possible, false if not (only SSL transaction).
        /// Please note, that the authentification can be true, but the liabilityshift is false. 
        /// The issuer has the right to deny the liabiliy shift during the authorization.You can continue to capture the payment here, but we recommend to cancel unsecure payments.
        /// </summary>
        public bool LiabilityShift { get; set; }

        /// <summary>
        /// Transaction Id, given by the MPI. References the 3D Secure process.
        /// Example: ARkvCgk5Y1t/BDFFXkUPGX9DUgs= for 3D Secure version 1 /
        /// 1ef5b3db-3b97-47df-8272-320d0bd18ab5 for 3D Secure version 2 
        /// </summary>
        public string Xid { get; set; }

        /// <summary>
        /// The Authentication Value generated by the card issuer's 3D Secure Access Control Server. Available only for 3D Secure 1.
        /// Example: AAABBIIFmAAAAAAAAAAAAAAAAAA= 
        /// </summary>
        public string VerificationValue { get; set; }
    }
}
